### ISSUE TITLE
head gallery break

### ISSUE THREAD

**Issue by exkc** [Zailer43/FZMM-Mod#56]
Version 0.2.13
![2024-08-17_22-54](https://github.com/user-attachments/assets/b962804f-d995-4ae4-ad00-30cbd6f1014c)

````
[22:52:58] [Render thread/ERROR]: [HeadGalleryScreen] Error while fetching category 'food-drinks'
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_7225$class_7874.method_57093(com.mojang.serialization.DynamicOps)" because the return value of "net.minecraft.class_1792$class_9635.method_59527()" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:761) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2214) ~[?:?]
	at fzmm.zailer.me.client.gui.head_gallery.HeadGalleryScreen.categoryButtonExecute(HeadGalleryScreen.java:167) ~[fzmm-mc1.21-0.2.13.jar:?]
	at fzmm.zailer.me.client.gui.head_gallery.HeadGalleryScreen.lambda$restoreMemento$23(HeadGalleryScreen.java:442) ~[fzmm-mc1.21-0.2.13.jar:?]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at fzmm.zailer.me.client.gui.head_gallery.HeadGalleryScreen.restoreMemento(HeadGalleryScreen.java:442) ~[fzmm-mc1.21-0.2.13.jar:?]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at fzmm.zailer.me.client.gui.BaseFzmmScreen.build(BaseFzmmScreen.java:75) ~[fzmm-mc1.21-0.2.13.jar:?]
	at fzmm.zailer.me.client.gui.BaseFzmmScreen.build(BaseFzmmScreen.java:45) ~[fzmm-mc1.21-0.2.13.jar:?]
	at io.wispforest.owo.ui.base.BaseOwoScreen.method_25426(BaseOwoScreen.java:91) ~[owo-lib-0.12.10+1.21.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1143) ~[client-intermediary.jar:?]
	at fzmm.zailer.me.client.gui.main.MainScreen.lambda$setupButtonsCallbacks$10(MainScreen.java:52) ~[fzmm-mc1.21-0.2.13.jar:?]
	at io.wispforest.owo.ui.component.ButtonComponent.lambda$onPress$1(ButtonComponent.java:59) ~[owo-lib-0.12.10+1.21.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:141) ~[client-intermediary.jar:?]
	at io.wispforest.owo.ui.component.VanillaWidgetComponent.onMouseDown(VanillaWidgetComponent.java:151) ~[owo-lib-0.12.10+1.21.jar:?]
	at net.minecraft.class_339.onMouseDown(class_339.java:1151) ~[client-intermediary.jar:?]
	at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170) ~[owo-lib-0.12.10+1.21.jar:?]
	at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212) ~[owo-lib-0.12.10+1.21.jar:?]
	at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170) ~[owo-lib-0.12.10+1.21.jar:?]
	at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212) ~[owo-lib-0.12.10+1.21.jar:?]
	at io.wispforest.owo.ui.container.ScrollContainer.onMouseDown(ScrollContainer.java:205) ~[owo-lib-0.12.10+1.21.jar:?]
	at io.wispforest.owo.ui.core.ParentComponent.onMouseDown(ParentComponent.java:170) ~[owo-lib-0.12.10+1.21.jar:?]
	at io.wispforest.owo.ui.base.BaseParentComponent.onMouseDown(BaseParentComponent.java:212) ~[owo-lib-0.12.10+1.21.jar:?]
	at io.wispforest.owo.ui.core.OwoUIAdapter.method_25402(OwoUIAdapter.java:218) ~[owo-lib-0.12.10+1.21.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:431) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:196) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.redirect$cok001$viafabricplus$storeEvent(class_312.java:2557) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:196) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.3.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) [lwjgl-glfw-3.3.3.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150) [client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168) [client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:303) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1307) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_7225$class_7874.method_57093(com.mojang.serialization.DynamicOps)" because the return value of "net.minecraft.class_1792$class_9635.method_59527()" is null
	at zabi.minecraft.nbttooltip.NBTTooltip.onInjectTooltip(NBTTooltip.java:160) ~[nbttooltip-1.2.0.jar:?]
	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:35) ~[fabric-item-api-v1-11.0.0+afdfc921d1-8389d83bc483cd81.jar:?]
	at net.minecraft.class_1799.handler$zoa000$fabric-item-api-v1$getTooltip(class_1799.java:2636) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.method_7950(class_1799.java:807) ~[client-intermediary.jar:?]
	at fzmm.zailer.me.client.gui.components.GiveItemComponent.<init>(GiveItemComponent.java:18) ~[fzmm-mc1.21-0.2.13.jar:?]
	at fzmm.zailer.me.client.gui.head_gallery.HeadGalleryScreen.getPageItems(HeadGalleryScreen.java:364) ~[fzmm-mc1.21-0.2.13.jar:?]
	at fzmm.zailer.me.client.gui.head_gallery.HeadGalleryScreen.setPage(HeadGalleryScreen.java:317) ~[fzmm-mc1.21-0.2.13.jar:?]
	at fzmm.zailer.me.client.gui.head_gallery.HeadGalleryScreen.lambda$restoreMemento$22(HeadGalleryScreen.java:447) ~[fzmm-mc1.21-0.2.13.jar:?]
	at fzmm.zailer.me.client.gui.head_gallery.HeadGalleryScreen.lambda$categoryButtonExecute$7(HeadGalleryScreen.java:186) ~[fzmm-mc1.21-0.2.13.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:108) ~[client-intermediary.jar:?]
	at fzmm.zailer.me.client.gui.head_gallery.HeadGalleryScreen.lambda$categoryButtonExecute$8(HeadGalleryScreen.java:168) ~[fzmm-mc1.21-0.2.13.jar:?]
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
	... 50 more
````

**Comment by Zailer43** [comment]
The error seems to be an incompatibility with [NBT Tooltip](https://modrinth.com/mod/nbttooltip), a workaround is to disable extra information in the tooltips using F3+H. It will be fixed in the next version of FZMM.

Thanks for reporting

**Comment by exkc** [comment]
it is fixed latest commit

**Comment by Zailer43** [comment]
Fixed in the [latest release](https://modrinth.com/mod/fzmm/version/0.2.14)
