### ISSUE TITLE
Bug list 

### ISSUE THREAD

**Issue by FurnyGo** [Zailer43/FZMM-Mod#7]
1. The head generator and the skin search by nickname in the Player statue do not work
![image](https://user-images.githubusercontent.com/68079109/188324841-a7f92bbc-589c-4698-bb93-8c898b4a9d59.png)
---
2. The values in Brightness and hueStep have a lot of extra unnecessary digits by default
![image](https://user-images.githubusercontent.com/68079109/188324351-dc56438f-ad94-4e85-a3d3-6d64ff3a15df.png)
---
3. If the image is too large in "Book tooltip", this happens:
![image](https://user-images.githubusercontent.com/68079109/188324409-e40353e0-ef02-4728-aa4d-d96e3789a596.png)
---
4. The screen of the head generator has no background dimming
---
5. The second line in the description of the Armor Stand for Player Statue has no color
![image](https://user-images.githubusercontent.com/68079109/188324588-903fe324-e96d-4606-b965-b184edd8185c.png)
---
6. "preserveImageAspectRatioInImagetext:false" does not work when the image is already loaded
---
7. I want to make a translation of this mod, but the buttons in the main menu do not change the size for the text
But at the same time in other sections everything is fine
![image](https://user-images.githubusercontent.com/68079109/188324781-20775b79-eb0c-4518-a7d7-66dd8df31955.png)
![image](https://user-images.githubusercontent.com/68079109/188324786-9f1903f9-8072-4864-9ce0-5a1d119fc460.png)
---
8. The image in the Book Tooltip has an unnecessary line at the end and a distance at the beginning that breaks the picture
![image](https://user-images.githubusercontent.com/68079109/188324929-b1a38f84-018f-4308-96a5-8852429106c3.png)

**Comment by Zailer43** [comment]
> 1. The head generator and the skin search by nickname in the Player statue do not work

that should be fixed for alpha 3 in https://github.com/Zailer43/FZMM-Mod/commit/3c7dc4dbdebfd1b62404574638b996c65baf450a

> 2. The values in Brightness and hueStep have a lot of extra unnecessary digits by default

thanks, fixed

> 3. If the image is too large in "Book tooltip", this happens:

thanks, fixed

> 4. The screen of the head generator has no background dimming

thanks, fixed

> 5. The second line in the description of the Armor Stand for Player Statue has no color

fixed and added translation

> 6. "preserveImageAspectRatioInImagetext:false" does not work when the image is already loaded

thanks, fixed

> 8. The image in the Book Tooltip has an unnecessary line at the end and a distance at the beginning that breaks the picture

I can't fix the start line, it's something from the minecraft tooltip to delimit the name and lore
extra line break is fixed

> 7. I want to make a translation of this mod, but the buttons in the main menu do not change the size for the text
> But at the same time in other sections everything is fine

thanks, fixed

**Comment by Zailer43** [comment]
try to replicate 1 with https://github.com/Zailer43/FZMM-Mod/actions/runs/2989163492

**Comment by FurnyGo** [comment]
> try to replicate 1 with https://github.com/Zailer43/FZMM-Mod/actions/runs/2989163492

![image](https://user-images.githubusercontent.com/68079109/188329274-d6b12dc4-704b-492e-86f7-1a14dc67e0e5.png)
does not work

**Comment by FurnyGo** [comment]
9. "Back" does not return to the main screen, but closes the menu completely

**Comment by Zailer43** [comment]
> > try to replicate 1 with https://github.com/Zailer43/FZMM-Mod/actions/runs/2989163492
> 
> ![image](https://user-images.githubusercontent.com/68079109/188329274-d6b12dc4-704b-492e-86f7-1a14dc67e0e5.png) does not work

try this and when it doesn't work send me the logs
https://github.com/Zailer43/FZMM-Mod/actions/runs/2989207746

**Comment by FurnyGo** [comment]
```[23:12:07] [Thread-9/INFO]: [STDERR]: com.google.gson.JsonIOException: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseReader(JsonParser.java:68)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at fzmm.zailer.me.utils.FzmmUtils.getPlayerUuid(FzmmUtils.java:224)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at fzmm.zailer.me.utils.FzmmUtils.getPlayerSkinFromMojang(FzmmUtils.java:184)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at fzmm.zailer.me.utils.FzmmUtils.getPlayerSkin(FzmmUtils.java:179)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at fzmm.zailer.me.client.gui.options.ImageOption.lambda$loadImage$0(ImageOption.java:152)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:12:07] [Thread-9/INFO]: [STDERR]: Caused by: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:263)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:183)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1289)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1327)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:537)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	at com.google.gson.JsonParser.parseReader(JsonParser.java:61)
[23:12:07] [Thread-9/INFO]: [STDERR]: 	... 5 more

**Comment by FurnyGo** [comment]
and this
```
[23:13:47] [Thread-10/INFO]: [STDERR]: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:371)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:309)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1505)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1420)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at fzmm.zailer.me.utils.FzmmUtils.httpGetRequest(FzmmUtils.java:113)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at fzmm.zailer.me.utils.FzmmUtils.getPlayerSkinFromMojang(FzmmUtils.java:185)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at fzmm.zailer.me.utils.FzmmUtils.getPlayerSkin(FzmmUtils.java:179)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at fzmm.zailer.me.client.gui.options.ImageOption.lambda$loadImage$0(ImageOption.java:152)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[23:13:47] [Thread-10/INFO]: [STDERR]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	... 28 more
[23:13:47] [Thread-10/INFO]: [STDERR]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
[23:13:47] [Thread-10/INFO]: [STDERR]: 	... 33 more

**Comment by Zailer43** [comment]
well, no way, anyway I wanted to remove that library since it weighs about 800kb

**Comment by FurnyGo** [comment]
![image](https://user-images.githubusercontent.com/68079109/188330524-a4fe2f9f-39b4-407a-bca0-179c5574ceaf.png)
The background is too light and the buttons are uneven

**Comment by FurnyGo** [comment]
![image](https://user-images.githubusercontent.com/68079109/188330609-ac42c78b-e8f3-41b9-9157-2474c3e80af9.png)
![image](https://user-images.githubusercontent.com/68079109/188330612-f08a12ff-d18f-4618-b61d-0f5ab62da4c3.png)
The maximum value is similar to point 2

**Comment by Zailer43** [comment]
> ![image](https://user-images.githubusercontent.com/68079109/188330524-a4fe2f9f-39b4-407a-bca0-179c5574ceaf.png) The background is too light and the buttons are uneven

the background is darker than in the other screens but I'm using the minecraft vanilla background while in the others I use the malilib one, I didn't make this screen with malilib since I don't know how

**Comment by Zailer43** [comment]
> ![image](https://user-images.githubusercontent.com/68079109/188330609-ac42c78b-e8f3-41b9-9157-2474c3e80af9.png) ![image](https://user-images.githubusercontent.com/68079109/188330612-f08a12ff-d18f-4618-b61d-0f5ab62da4c3.png) The maximum value is similar to point 2

burn the floats, use doubles, my new motto

**Comment by FurnyGo** [comment]
10. When you change the fzmmMainGui key, the menu opens only when you press the changed key and Z, not just the changed key
